#!/usr/bin/env python3
# Generates lib/src/unicode15.ts — the Unicode 15.0 persona repertoire
# (Identity 0.50 section 6.2). Requires CPython with unicodedata 15.1.0
# (Python 3.13). 15.1 added exactly 627 characters over 15.0 — CJK
# Extension I (U+2EBF0..U+2EE5D), the ideographic description characters
# U+2FFC..U+2FFF and U+31EF — which this script subtracts to reconstruct
# 15.0 precisely. Output is deterministic; the checked-in file must be
# byte-identical to a fresh run (that is what makes the pin auditable).
import unicodedata, sys

assert unicodedata.unidata_version == '15.1.0', unicodedata.unidata_version
ADDED_151 = set(range(0x2EBF0, 0x2EE5E)) | {0x2FFC, 0x2FFD, 0x2FFE, 0x2FFF, 0x31EF}
assert len(ADDED_151) == 627, len(ADDED_151)

ranges, start = [], None
for cp in range(0x110000):
    allowed = cp not in ADDED_151 and unicodedata.category(chr(cp)) not in ('Cn', 'Cc', 'Cf', 'Cs')
    if allowed and start is None: start = cp
    elif not allowed and start is not None: ranges.append((start, cp - 1)); start = None
if start is not None: ranges.append((start, 0x10FFFF))
total = sum(b - a + 1 for a, b in ranges)

parts, prev_end = [], -1
for a, b in ranges:
    parts.append(f"{a - prev_end - 1:x}:{b - a:x}"); prev_end = b
data = ",".join(parts)

TS = f"""// GENERATED by scripts/build-unicode15.py — DO NOT EDIT.
//
// The persona-name repertoire of Identity 0.50 §6.2, pinned to
// **Unicode 15.0**: every code point that is assigned in 15.0 and not of
// category Cc (control), Cf (format) or Cs (surrogate). The pin is what
// makes the derivable persona set identical across implementations and
// platform ICU versions — evaluating against the PLATFORM's tables was
// review-2 blocker B-1: Node 22 ships Unicode 16, so a name using a code
// point assigned after 15.0 derived an anchor on one runtime and was
// rejected on another.
//
// Provenance: generated from CPython's unicodedata (Unicode 15.1.0)
// minus the FULL 15.1 delta — CJK Extension I (U+2EBF0..U+2EE5D), the
// ideographic description characters U+2FFC..U+2FFF and U+31EF (627
// characters, per the 15.1 release notes) — which reconstructs 15.0
// exactly. {len(ranges)} ranges, {total} code points.
// Encoding: comma-separated "gap:length" hex pairs — gap to the previous
// range's end, length of the range minus one.

const DATA = '{data}'

const STARTS: number[] = []
const ENDS: number[] = []
{{
  let cp = -1
  for (const part of DATA.split(',')) {{
    const [gap, len] = part.split(':')
    const start = cp + parseInt(gap, 16) + 1
    cp = start + parseInt(len, 16)
    STARTS.push(start); ENDS.push(cp)
  }}
}}

/** Is this code point permitted in a persona name under the Unicode 15.0 pin? */
export function allowed15 (cp: number): boolean {{
  let lo = 0, hi = STARTS.length - 1
  while (lo <= hi) {{
    const mid = (lo + hi) >> 1
    if (cp < STARTS[mid]!) hi = mid - 1
    else if (cp > ENDS[mid]!) lo = mid + 1
    else return true
  }}
  return false
}}

/**
 * The White_Space property, Unicode 15.0 (25 code points, version-stable
 * in practice; pinned here all the same so no platform data is consulted).
 */
export const WHITE_SPACE_15 = new Set([
  0x9, 0xa, 0xb, 0xc, 0xd, 0x20, 0x85, 0xa0, 0x1680,
  0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007,
  0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f, 0x205f, 0x3000,
])
"""
with open('lib/src/unicode15.ts', 'w') as f:
    f.write(TS)
print(f"lib/src/unicode15.ts: {len(ranges)} ranges, {total} code points", file=sys.stderr)
